### PR TITLE
Kerrigan fixes

### LINKED ISSUE #1: Create svg sprite and connect it in footer

### LINKED ISSUE #16: Remove not used js and php
Chech this dir's:
theme/inc
theme/js
and also remove require this files in functions.php

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #1. Add SVG sprite. Add common styles for svg container. Change icons in footer ( widget ). Remove old social icons, add new one in svg.
Fix #16. Remove un used js & php files.

### CODE REVIEW

File: assets/svg/sprite.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    </svg>
+
+    <svg id="twitter" viewBox="0 0 13 14">
+        <path d="M12.656 3.188q-0.523 0.766-1.266 1.305 0.008 0.109 0.008 0.328 0 1.016-0.297 2.027t-0.902 1.941-1.441 1.645-2.016 1.141-2.523 0.426q-2.117 0-3.875-1.133 0.273 0.031 0.609 0.031 1.758 0 3.133-1.078-0.82-0.016-1.469-0.504t-0.891-1.246q0.258 0.039 0.477 0.039 0.336 0 0.664-0.086-0.875-0.18-1.449-0.871t-0.574-1.605v-0.031q0.531 0.297 1.141 0.32-0.516-0.344-0.82-0.898t-0.305-1.203q0-0.688 0.344-1.273 0.945 1.164 2.301 1.863t2.902 0.777q-0.062-0.297-0.062-0.578 0-1.047 0.738-1.785t1.785-0.738q1.094 0 1.844 0.797 0.852-0.164 1.602-0.609-0.289 0.898-1.109 1.391 0.727-0.078 1.453-0.391z"></path>
+    </svg>
+
+    <svg id="livejournal" viewBox="0 0 304.999 304.999" >
+        <g>
```
Comment (Diadlo) [inline assets/svg/sprite.php]: Unneded `<g>...</g>`

File: core/deregister.php [hunk 2]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+Class POLITSTURM_DEREGISTER {
+
+	public static function deregister_styles()    {
+		//wp_deregister_style( 'amethyst-dashicons-style' );
```
Comment (Diadlo) [inline core/deregister.php]: Remove unused code?
